"""Shared contracts for the Daastaan monorepo.

Imported by the API service, the agent service, and (via generated OpenAPI types)
the frontends. Deliberately depends only on Pydantic so that adding it to a
service never drags in a database driver or an LLM SDK.
"""

from .editing import (
    ASPECT_SIZES,
    CAPTION_PRESETS,
    AspectRatio,
    AudioMix,
    CaptionFont,
    CaptionPosition,
    CaptionStyle,
    Corner,
    FrameFill,
    LineSpan,
    Motion,
    RenderStatus,
    TitleCard,
    TrimRange,
    VideoEditManifest,
    Watermark,
    build_timeline,
    manifest_digest,
    timeline_duration_ms,
)
from .enums import (
    AssetKind,
    CharacterRole,
    ConsistencyCheckStatus,
    FeedbackStatus,
    IngestStatus,
    JobStatus,
    LineType,
    Scope,
    StageName,
    StoryStatus,
    UserRole,
    VoiceAge,
    VoiceGender,
)
from .events import (
    AssetEvent,
    CompleteEvent,
    FeedbackEvent,
    HeartbeatEvent,
    MusicStatusEvent,
    ProgressEvent,
    StageEvent,
    StagePreviewEvent,
    StageProgressEvent,
    StageTokensEvent,
    progress_event_adapter,
)
from .languages import language_name
from .models import (
    Character,
    CharacterRegistryOutput,
    ConsistencyAnalysisOutput,
    ConsistencyFinding,
    ConsistencyFindingOutput,
    DialogueLine,
    DialogueScriptOutput,
    EmotionTaggingOutput,
    MediaAsset,
    MoodClassificationOutput,
    NarratorPersona,
    NarratorPersonaOutput,
    RegenDirective,
    Scene,
    StoryCleanupOutput,
    StoryUnderstandingOutput,
    ValidatedDirective,
    VoiceAssignment,
)
from .stages import (
    AGENT_STAGES,
    FANOUT_STAGES,
    PIPELINE_STAGES,
    downstream_from,
    is_fanout,
    is_valid_entry,
    plan_stages,
    stage_index,
)
from .state import StoryState
from .tasks import STAGE_QUEUE, Queue, TaskName

__all__ = [
    "AGENT_STAGES",
    "ASPECT_SIZES",
    "CAPTION_PRESETS",
    "language_name",
    "FANOUT_STAGES",
    "PIPELINE_STAGES",
    "STAGE_QUEUE",
    "AspectRatio",
    "AssetEvent",
    "AssetKind",
    "AudioMix",
    "CaptionFont",
    "CaptionPosition",
    "CaptionStyle",
    "Character",
    "CharacterRegistryOutput",
    "CharacterRole",
    "CompleteEvent",
    "ConsistencyCheckStatus",
    "ConsistencyAnalysisOutput",
    "ConsistencyFinding",
    "ConsistencyFindingOutput",
    "Corner",
    "DialogueLine",
    "DialogueScriptOutput",
    "EmotionTaggingOutput",
    "FeedbackEvent",
    "FeedbackStatus",
    "FrameFill",
    "HeartbeatEvent",
    "IngestStatus",
    "JobStatus",
    "LineSpan",
    "LineType",
    "MediaAsset",
    "MoodClassificationOutput",
    "Motion",
    "MusicStatusEvent",
    "NarratorPersona",
    "NarratorPersonaOutput",
    "ProgressEvent",
    "Queue",
    "RegenDirective",
    "RenderStatus",
    "Scene",
    "Scope",
    "StageEvent",
    "StageName",
    "StagePreviewEvent",
    "StageProgressEvent",
    "StageTokensEvent",
    "StoryCleanupOutput",
    "StoryState",
    "StoryStatus",
    "StoryUnderstandingOutput",
    "TaskName",
    "TitleCard",
    "TrimRange",
    "UserRole",
    "ValidatedDirective",
    "VideoEditManifest",
    "VoiceAge",
    "VoiceAssignment",
    "VoiceGender",
    "Watermark",
    "build_timeline",
    "downstream_from",
    "is_fanout",
    "is_valid_entry",
    "manifest_digest",
    "plan_stages",
    "progress_event_adapter",
    "stage_index",
    "timeline_duration_ms",
]
