/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as ProcessingIdRouteImport } from './routes/processing.$id'
import { Route as StoryIdIndexRouteImport } from './routes/story.$id.index'
import { Route as StoryIdVoicesRouteImport } from './routes/story.$id.voices'
import { Route as StoryIdUnderstandingRouteImport } from './routes/story.$id.understanding'
import { Route as StoryIdPlayerRouteImport } from './routes/story.$id.player'
import { Route as StoryIdPersonasRouteImport } from './routes/story.$id.personas'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingIdRoute = ProcessingIdRouteImport.update({
  id: '/processing/$id',
  path: '/processing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdIndexRoute = StoryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoryIdRoute,
} as any)
const StoryIdVoicesRoute = StoryIdVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => StoryIdRoute,
} as any)
const StoryIdUnderstandingRoute = StoryIdUnderstandingRouteImport.update({
  id: '/understanding',
  path: '/understanding',
  getParentRoute: () => StoryIdRoute,
} as any)
const StoryIdPlayerRoute = StoryIdPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => StoryIdRoute,
} as any)
const StoryIdPersonasRoute = StoryIdPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => StoryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/story/$id': typeof StoryIdRouteWithChildren
  '/story/$id/personas': typeof StoryIdPersonasRoute
  '/story/$id/player': typeof StoryIdPlayerRoute
  '/story/$id/understanding': typeof StoryIdUnderstandingRoute
  '/story/$id/voices': typeof StoryIdVoicesRoute
  '/story/$id/': typeof StoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/story/$id/personas': typeof StoryIdPersonasRoute
  '/story/$id/player': typeof StoryIdPlayerRoute
  '/story/$id/understanding': typeof StoryIdUnderstandingRoute
  '/story/$id/voices': typeof StoryIdVoicesRoute
  '/story/$id': typeof StoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/processing/$id': typeof ProcessingIdRoute
  '/story/$id': typeof StoryIdRouteWithChildren
  '/story/$id/personas': typeof StoryIdPersonasRoute
  '/story/$id/player': typeof StoryIdPlayerRoute
  '/story/$id/understanding': typeof StoryIdUnderstandingRoute
  '/story/$id/voices': typeof StoryIdVoicesRoute
  '/story/$id/': typeof StoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/library'
    | '/observability'
    | '/settings'
    | '/upload'
    | '/processing/$id'
    | '/story/$id'
    | '/story/$id/personas'
    | '/story/$id/player'
    | '/story/$id/understanding'
    | '/story/$id/voices'
    | '/story/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/library'
    | '/observability'
    | '/settings'
    | '/upload'
    | '/processing/$id'
    | '/story/$id/personas'
    | '/story/$id/player'
    | '/story/$id/understanding'
    | '/story/$id/voices'
    | '/story/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/library'
    | '/observability'
    | '/settings'
    | '/upload'
    | '/processing/$id'
    | '/story/$id'
    | '/story/$id/personas'
    | '/story/$id/player'
    | '/story/$id/understanding'
    | '/story/$id/voices'
    | '/story/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  ObservabilityRoute: typeof ObservabilityRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  ProcessingIdRoute: typeof ProcessingIdRoute
  StoryIdRoute: typeof StoryIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$id': {
      id: '/processing/$id'
      path: '/processing/$id'
      fullPath: '/processing/$id'
      preLoaderRoute: typeof ProcessingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id/': {
      id: '/story/$id/'
      path: '/'
      fullPath: '/story/$id/'
      preLoaderRoute: typeof StoryIdIndexRouteImport
      parentRoute: typeof StoryIdRoute
    }
    '/story/$id/voices': {
      id: '/story/$id/voices'
      path: '/voices'
      fullPath: '/story/$id/voices'
      preLoaderRoute: typeof StoryIdVoicesRouteImport
      parentRoute: typeof StoryIdRoute
    }
    '/story/$id/understanding': {
      id: '/story/$id/understanding'
      path: '/understanding'
      fullPath: '/story/$id/understanding'
      preLoaderRoute: typeof StoryIdUnderstandingRouteImport
      parentRoute: typeof StoryIdRoute
    }
    '/story/$id/player': {
      id: '/story/$id/player'
      path: '/player'
      fullPath: '/story/$id/player'
      preLoaderRoute: typeof StoryIdPlayerRouteImport
      parentRoute: typeof StoryIdRoute
    }
    '/story/$id/personas': {
      id: '/story/$id/personas'
      path: '/personas'
      fullPath: '/story/$id/personas'
      preLoaderRoute: typeof StoryIdPersonasRouteImport
      parentRoute: typeof StoryIdRoute
    }
  }
}

interface StoryIdRouteChildren {
  StoryIdPersonasRoute: typeof StoryIdPersonasRoute
  StoryIdPlayerRoute: typeof StoryIdPlayerRoute
  StoryIdUnderstandingRoute: typeof StoryIdUnderstandingRoute
  StoryIdVoicesRoute: typeof StoryIdVoicesRoute
  StoryIdIndexRoute: typeof StoryIdIndexRoute
}

const StoryIdRouteChildren: StoryIdRouteChildren = {
  StoryIdPersonasRoute: StoryIdPersonasRoute,
  StoryIdPlayerRoute: StoryIdPlayerRoute,
  StoryIdUnderstandingRoute: StoryIdUnderstandingRoute,
  StoryIdVoicesRoute: StoryIdVoicesRoute,
  StoryIdIndexRoute: StoryIdIndexRoute,
}

const StoryIdRouteWithChildren =
  StoryIdRoute._addFileChildren(StoryIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  ObservabilityRoute: ObservabilityRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  ProcessingIdRoute: ProcessingIdRoute,
  StoryIdRoute: StoryIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
