/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only. Kept dependency-free so a database blip cannot make the
         *     container look dead to an orchestrator.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness. Reports each dependency separately so a failure points at the
         *     thing that is actually broken.
         */
        get: operations["readiness_api_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["list_stories_api_stories_get"];
        put?: never;
        /** Create Story */
        post: operations["create_story_api_stories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story */
        get: operations["get_story_api_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_api_stories__story_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Load a historical version's immutable timeline for the Time Machine.
         *
         *     The story dependency has already checked ownership. The additional story-id
         *     predicate prevents a caller who knows another version UUID from using this
         *     route to read it or to make it a fork parent.
         */
        get: operations["get_version_api_stories__story_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Progress
         * @description Polling endpoint for the progress stepper. The WebSocket is an
         *     enhancement; this is the path that always works.
         */
        get: operations["get_progress_api_stories__story_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate
         * @description Explicit, deterministic regeneration.
         *
         *     The stage plan is computed from the registry rather than taken from the
         *     request, so a caller cannot name an arbitrary re-entry point.
         */
        post: operations["regenerate_api_stories__story_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feedback
         * @description Revision history for the story.
         *
         *     Carries the interpreted directive and any failure reason, so the studio can
         *     tell the user what their note was understood to mean instead of leaving them
         *     guessing whether it landed.
         */
        get: operations["list_feedback_api_stories__story_id__feedback_get"];
        put?: never;
        /**
         * Submit Feedback
         * @description Free-text feedback.
         *
         *     The text is only stored here. Interpreting it into a regeneration directive
         *     happens in the agent service, and the resulting directive is re-validated
         *     against the stage registry before any work is dispatched - the API never
         *     trusts the model to choose what runs.
         */
        post: operations["submit_feedback_api_stories__story_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/consistency-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Consistency Checks
         * @description Return the recent reviews for the current version only.
         *
         *     A result for an older branch must never be displayed as a review of the
         *     current ending, so version is part of the query rather than just the story.
         */
        get: operations["list_consistency_checks_api_stories__story_id__consistency_checks_get"];
        put?: never;
        /**
         * Create Consistency Check
         * @description Queue one idempotent-in-flight, lightweight continuity review.
         */
        post: operations["create_consistency_check_api_stories__story_id__consistency_checks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Asset
         * @description Serve audio and images through the API rather than handing out storage
         *     URLs, so ownership is re-checked on every fetch and artifacts are never
         *     publicly readable.
         *
         *     Range support is not optional for the audio player: an element that cannot
         *     issue byte ranges has to refetch from zero to move the playhead, which is
         *     indistinguishable from restarting the track.
         */
        get: operations["stream_asset_api_media__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Settings */
        get: operations["list_settings_api_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert Setting
         * @description Runtime knobs: per-stage model overrides, voice presets, feature flags,
         *     budget cap. Workers read these at task time, so changes take effect on the
         *     next task without a redeploy.
         */
        put: operations["upsert_setting_api_admin_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost Summary */
        get: operations["cost_summary_api_admin_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Accounts with what each has spent, so a runaway user is visible from the
         *     list rather than only after drilling in.
         */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Costs */
        get: operations["user_costs_api_admin_users__user_id__costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Role */
        put: operations["set_role_api_admin_users__user_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Stories */
        get: operations["list_all_stories_api_admin_stories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stories/{story_id}/flag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flag Story */
        post: operations["flag_story_api_admin_stories__story_id__flag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Every pipeline execution, newest first.
         *
         *     A run is a `StoryVersion` rolled up from the `jobs` and `cost_ledger` rows it
         *     produced. The `pipeline_runs` table this used to read is never written to by
         *     anything, which is why the tab was always empty.
         */
        get: operations["list_runs_api_admin_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_admin_runs__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observability/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Observability Jobs */
        get: operations["observability_jobs_api_observability_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description No user-preferences table exists yet, so this is a non-persistent default.
         */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Preview Settings
         * @description Echo settings for a live preview; intentionally does not write to the DB.
         */
        patch: operations["preview_settings_api_settings_patch"];
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{ingest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingest */
        get: operations["get_ingest_api_ingest__ingest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_api_stories__story_id__exports_get"];
        put?: never;
        /** Create Export */
        post: operations["create_export_api_stories__story_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/bgm/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bgm Exports */
        get: operations["list_bgm_exports_api_stories__story_id__bgm_exports_get"];
        put?: never;
        /** Create Bgm Export */
        post: operations["create_bgm_export_api_stories__story_id__bgm_exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Story Events
         * @description Server-sent progress events.
         *
         *     `EventSource` cannot set headers, but it does send cookies for a same-origin
         *     request, and the web client reaches the API through the Vite proxy - so the
         *     normal session cookie authenticates this exactly like any other GET.
         */
        get: operations["story_events_api_stories__story_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminSettingIn */
        AdminSettingIn: {
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /** AdminSettingOut */
        AdminSettingOut: {
            /** Key */
            key: string;
            /** Value */
            value: {
                [key: string]: unknown;
            };
            /** Updated By */
            updated_by: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AssetCountOut */
        AssetCountOut: {
            /** Kind */
            kind: string;
            /** Count */
            count: number;
            /** Duration Ms */
            duration_ms: number;
        };
        /** AssetOut */
        AssetOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Line Id */
            line_id: string | null;
            /** Scene Id */
            scene_id: string | null;
            /** Content Type */
            content_type: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Url */
            url: string;
        };
        /** AuditLog */
        AuditLog: {
            /** Id */
            id?: string;
            /** Actor User Id */
            actor_user_id?: string | null;
            /** Action */
            action: string;
            /** Target Type */
            target_type?: string | null;
            /** Target Id */
            target_id?: string | null;
            /** Metadata Json */
            metadata_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** Body_upload_api_ingest_post */
        Body_upload_api_ingest_post: {
            /** File */
            file: string;
        };
        /**
         * ConsistencyCheckOut
         * @description Safe projection of one read-only continuity review.
         *
         *     Findings are already strict-schema validated and reference-checked by the
         *     worker. The API still validates them through this DTO before returning them
         *     so a malformed database value can never become arbitrary client content.
         */
        ConsistencyCheckOut: {
            /** Id */
            id: string;
            /** Story Id */
            story_id: string;
            /** Version Id */
            version_id: string;
            status: components["schemas"]["ConsistencyCheckStatus"];
            /** Task Id */
            task_id: string | null;
            /** Summary */
            summary: string | null;
            /** Findings */
            findings: components["schemas"]["ConsistencyFinding"][];
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * ConsistencyCheckStatus
         * @description Lifecycle of a read-only Plot Hole Hunter request.
         * @enum {string}
         */
        ConsistencyCheckStatus: "pending" | "running" | "succeeded" | "failed";
        /**
         * ConsistencyFinding
         * @description A checked, user-safe finding persisted by the worker and returned by API.
         */
        ConsistencyFinding: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "warning";
            /**
             * Type
             * @enum {string}
             */
            type: "knowledge" | "timeline" | "character" | "causality" | "continuity";
            /** Scene Id */
            scene_id: string;
            /** Line Id */
            line_id: string | null;
            /** Explanation */
            explanation: string;
            /** Suggestion */
            suggestion: string;
        };
        /** CostRow */
        CostRow: {
            /** Label */
            label: string;
            /** Calls */
            calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** CostSummaryOut */
        CostSummaryOut: {
            /** Total Usd */
            total_usd: number;
            /** Budget Cap Usd */
            budget_cap_usd: number;
            /** Remaining Usd */
            remaining_usd: number;
            /**
             * Cache Savings Usd
             * @default 0
             */
            cache_savings_usd: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /** By Stage */
            by_stage: components["schemas"]["CostRow"][];
            /** By Model */
            by_model: components["schemas"]["CostRow"][];
        };
        /** CreateStoryRequest */
        CreateStoryRequest: {
            /** Raw Text */
            raw_text: string;
            /** Genre Hint */
            genre_hint?: string | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Output Format
             * @default audio
             * @enum {string}
             */
            output_format: "audio" | "video" | "both";
        };
        /** DailySpendOut */
        DailySpendOut: {
            /** Day */
            day: string;
            /** Cost Usd */
            cost_usd: number;
            /** Calls */
            calls: number;
        };
        /** DispatchAccepted */
        DispatchAccepted: {
            /** Story Id */
            story_id: string;
            /** Version Id */
            version_id: string;
            /** Stages */
            stages: string[];
            /** Task Id */
            task_id: string;
        };
        /** ExportFormatOut */
        ExportFormatOut: {
            /** Format */
            format: string;
            /** Ready */
            ready: boolean;
            /** Url */
            url: string | null;
            /** Size Bytes */
            size_bytes: number | null;
            /** Label */
            label: string;
            /** Content Type */
            content_type: string;
            /** Detail */
            detail: string;
            /** Recommended */
            recommended: boolean;
        };
        /** ExportOut */
        ExportOut: {
            /** Format */
            format: string;
            /** Ready */
            ready: boolean;
            /** Url */
            url: string | null;
            /** Size Bytes */
            size_bytes: number | null;
        };
        /** ExportRequest */
        ExportRequest: {
            /** Format */
            format: string;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /** Id */
            id: string;
            /** Raw Text */
            raw_text: string;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Directive Json */
            directive_json: {
                [key: string]: unknown;
            } | null;
            /** Resulting Version Id */
            resulting_version_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeedbackRequest
         * @description Free text. The Feedback Interpreter turns it into a directive, which is
         *     then re-validated server-side before anything is dispatched.
         */
        FeedbackRequest: {
            /** Raw Text */
            raw_text: string;
            /** Target Id */
            target_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestAccepted */
        IngestAccepted: {
            /** Ingest Id */
            ingest_id: string;
            /** Filename */
            filename: string;
        };
        /** IngestOut */
        IngestOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Status */
            status: string;
            /** Method */
            method: string | null;
            /** Page Count */
            page_count: number | null;
            /** Raw Chars */
            raw_chars: number | null;
            /** Cleaned Text */
            cleaned_text: string | null;
            /** Title Hint */
            title_hint: string | null;
            /** Genre Hint */
            genre_hint: string | null;
            /** Notes */
            notes: string | null;
            /** Error */
            error: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Attempt */
            attempt: number;
            /** Error */
            error: string | null;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ModelCostOut */
        ModelCostOut: {
            /** Label */
            label: string;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Hits */
            cache_hits: number;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Story Id */
            story_id: string;
            /** Version Id */
            version_id: string | null;
            /** Status */
            status: string;
            /** Planned Stages */
            planned_stages: string[];
            /** Jobs */
            jobs: components["schemas"]["JobOut"][];
            /**
             * Stage Progress
             * @default []
             */
            stage_progress: components["schemas"]["StageProgressOut"][];
        };
        /**
         * RegenerateRequest
         * @description The explicit, button-driven path. Deterministic, so it is the safe route
         *     to use during a live demo.
         */
        RegenerateRequest: {
            scope: components["schemas"]["Scope"];
            target_stage: components["schemas"]["StageName"];
            /** Target Id */
            target_id?: string | null;
            /**
             * Instruction Delta
             * @default
             */
            instruction_delta: string;
            /** Base Version Id */
            base_version_id?: string | null;
            /** Expected Current Version Id */
            expected_current_version_id?: string | null;
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Role */
            role: string;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /** Version Id */
            version_id: string;
            /** Story Id */
            story_id: string;
            /** Story Title */
            story_title: string | null;
            /** User Id */
            user_id: string | null;
            /** User Email */
            user_email: string | null;
            /** Version Number */
            version_number: number;
            /** Genre */
            genre: string | null;
            /** Mood */
            mood: string | null;
            /** Parent Version Id */
            parent_version_id: string | null;
            /** Is Regen */
            is_regen: boolean;
            /** Directive */
            directive: {
                [key: string]: unknown;
            } | null;
            /** Feedback Text */
            feedback_text: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Calls */
            calls: number;
            /** Cache Hits */
            cache_hits: number;
            /** Stages */
            stages: components["schemas"]["RunStageOut"][];
            /** By Model */
            by_model: components["schemas"]["ModelCostOut"][];
            /** Assets */
            assets: components["schemas"]["AssetCountOut"][];
        };
        /** RunStageOut */
        RunStageOut: {
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Attempt */
            attempt: number;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Calls */
            calls: number;
            /** Cache Hits */
            cache_hits: number;
        };
        /**
         * RunSummaryOut
         * @description One `StoryVersion` execution, rolled up from jobs and the cost ledger.
         */
        RunSummaryOut: {
            /** Version Id */
            version_id: string;
            /** Story Id */
            story_id: string;
            /** Story Title */
            story_title: string | null;
            /** User Id */
            user_id: string | null;
            /** User Email */
            user_email: string | null;
            /** Version Number */
            version_number: number;
            /** Genre */
            genre: string | null;
            /** Mood */
            mood: string | null;
            /** Is Regen */
            is_regen: boolean;
            /** Regen Scope */
            regen_scope: string | null;
            /** Regen Stage */
            regen_stage: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Stage Count */
            stage_count: number;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Hits */
            cache_hits: number;
            /** Error */
            error: string | null;
        };
        /**
         * Scope
         * @description Blast radius of a regeneration request.
         * @enum {string}
         */
        Scope: "line" | "character" | "scene" | "music" | "full_story";
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * StageName
         * @description Pipeline stages. Values are persisted and appear in task payloads, so treat
         *     them as a wire format: renaming one is a breaking change.
         * @enum {string}
         */
        StageName: "mood_classification" | "story_understanding" | "character_registry" | "dialogue_attribution" | "emotion_tagging" | "narrator_persona" | "voice_assignment" | "tts_synthesis" | "image_generation" | "music_generation" | "assembly" | "video_composition";
        /**
         * StageProgressOut
         * @description How far through a fan-out stage this run is.
         *
         *     The same numbers the `stage_progress` event carries, recomputed from
         *     `media_assets` so the polling fallback agrees with the live stream instead of
         *     dropping back to an all-or-nothing stage chip when the stream is unavailable.
         */
        StageProgressOut: {
            /** Stage */
            stage: string;
            /** Completed */
            completed: number;
            /** Total */
            total: number;
        };
        /** StoryDetailOut */
        StoryDetailOut: {
            story: components["schemas"]["StoryOut"];
            version: components["schemas"]["VersionOut"] | null;
            /** State */
            state: {
                [key: string]: unknown;
            } | null;
            /** Assets */
            assets: components["schemas"]["AssetOut"][];
        };
        /** StoryOut */
        StoryOut: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Status */
            status: string;
            /** Current Version Id */
            current_version_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StorySpendOut */
        StorySpendOut: {
            /** Story Id */
            story_id: string;
            /** Title */
            title: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Calls */
            calls: number;
        };
        /** UserCostDetailOut */
        UserCostDetailOut: {
            user: components["schemas"]["UserSummaryOut"];
            /** Daily */
            daily: components["schemas"]["DailySpendOut"][];
            /** By Stage */
            by_stage: components["schemas"]["CostRow"][];
            /** By Model */
            by_model: components["schemas"]["CostRow"][];
            /** By Story */
            by_story: components["schemas"]["StorySpendOut"][];
            /** Cache Savings Usd */
            cache_savings_usd: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserSummaryOut */
        UserSummaryOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Stories */
            stories: number;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cache Hits */
            cache_hits: number;
            /** Last Active At */
            last_active_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionOut */
        VersionOut: {
            /** Id */
            id: string;
            /** Story Id */
            story_id: string;
            /** Parent Version Id */
            parent_version_id: string | null;
            /** Version Number */
            version_number: number;
            /** Genre */
            genre: string | null;
            /** Mood */
            mood: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AssetEvent
         * @description One media artifact finished and is now fetchable.
         */
        AssetEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "asset";
            kind: components["schemas"]["AssetKind"];
            /**
             * Line Id
             * @default null
             */
            line_id: string | null;
            /**
             * Scene Id
             * @default null
             */
            scene_id: string | null;
            /**
             * Duration Ms
             * @default null
             */
            duration_ms: number | null;
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "line_audio" | "scene_image" | "music_bed" | "final_episode" | "final_video" | "episode_export" | "bgm_export";
        /**
         * CompleteEvent
         * @description The episode is playable. Terminal for a run.
         */
        CompleteEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "complete";
            /** Version Id */
            version_id: string;
        };
        /** FeedbackEvent */
        FeedbackEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "feedback";
            status: components["schemas"]["FeedbackStatus"];
            /** Feedback Id */
            feedback_id: string;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Version Id
             * @default null
             */
            version_id: string | null;
            /** @default null */
            scope: components["schemas"]["Scope"] | null;
            /** @default null */
            target_stage: components["schemas"]["StageName"] | null;
            /**
             * Target Id
             * @default null
             */
            target_id: string | null;
        };
        /**
         * FeedbackStatus
         * @description Outcome of interpreting one piece of free-text feedback.
         *
         *     Interpretation can fail on a decision rather than an outage - moderation
         *     refusing the text, or the model naming a stage that is not a legal entry
         *     point - so the attempt needs a durable outcome the user can be shown.
         * @enum {string}
         */
        FeedbackStatus: "pending" | "applied" | "failed";
        /**
         * HeartbeatEvent
         * @description Proof of liveness during a quiet stretch.
         *
         *     SSE sends a comment line instead, which `EventSource` never surfaces; this
         *     exists for the WebSocket path, where there is no comment syntax and a client
         *     otherwise cannot tell idle from dead.
         */
        HeartbeatEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "heartbeat";
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "pending" | "running" | "succeeded" | "failed" | "skipped";
        /**
         * MusicStatusEvent
         * @description The score degraded without the episode failing.
         */
        MusicStatusEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "music_status";
            /**
             * Status
             * @constant
             */
            status: "unavailable";
            /** Error */
            error: string;
        };
        /**
         * StageEvent
         * @description A stage changed status. The `jobs` table holds the same transition.
         */
        StageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage";
            stage: components["schemas"]["StageName"];
            status: components["schemas"]["JobStatus"];
            /**
             * Error
             * @default null
             */
            error: string | null;
        };
        /**
         * StagePreviewEvent
         * @description Content the model has produced so far, mid-call.
         *
         *     Emitted from the streaming structured-output parse, so the browser shows
         *     characters and scene titles appearing while the stage is still running instead
         *     of waiting for it to commit. `items` are display-ready strings and each is sent
         *     at most once per stage: the client appends, it does not replace.
         */
        StagePreviewEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage_preview";
            stage: components["schemas"]["StageName"];
            /** Label */
            label: string;
            /** Items */
            items?: string[];
        };
        /**
         * StageProgressEvent
         * @description Sub-stage progress for work that is a group of subtasks.
         *
         *     TTS and image generation fan out to one task per line and per scene. Without
         *     this the stage sits at `running` for the entire multi-minute fan-out, which is
         *     the largest single gap between what the pipeline is doing and what the user
         *     can see.
         *
         *     `total` is how many subtasks this run actually enqueued, not how many lines the
         *     story has: a regeneration that respeaks one line reports 1, not 40. `completed`
         *     is read from a Redis counter, so it is accurate even though the publishers are
         *     concurrent - but see the module docstring on ordering.
         */
        StageProgressEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage_progress";
            stage: components["schemas"]["StageName"];
            /** Completed */
            completed: number;
            /** Total */
            total: number;
        };
        /**
         * StageTokensEvent
         * @description Output-token count for a stage still in flight.
         *
         *     A stage can run a long time with nothing display-worthy to show - a long arc
         *     summary being drafted, for instance - and a UI with no signal during that
         *     window looks stalled. Deliberately just a counter: the cheapest honest proof
         *     that the model is still producing.
         */
        StageTokensEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage_tokens";
            stage: components["schemas"]["StageName"];
            /** Tokens */
            tokens: number;
        };
        ProgressEvent: components["schemas"]["StageEvent"] | components["schemas"]["StageProgressEvent"] | components["schemas"]["StagePreviewEvent"] | components["schemas"]["StageTokensEvent"] | components["schemas"]["AssetEvent"] | components["schemas"]["MusicStatusEvent"] | components["schemas"]["FeedbackEvent"] | components["schemas"]["CompleteEvent"] | components["schemas"]["HeartbeatEvent"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_api_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_stories_api_stories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"][];
                };
            };
        };
    };
    create_story_api_stories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_api_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_api_stories__story_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_stories__story_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_stories__story_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_stories__story_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feedback_api_stories__story_id__feedback_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_stories__story_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consistency_checks_api_stories__story_id__consistency_checks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistencyCheckOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_consistency_check_api_stories__story_id__consistency_checks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistencyCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_asset_api_media__asset_id__get: {
        parameters: {
            query?: {
                download?: boolean;
            };
            header?: {
                Range?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_settings_api_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingOut"][];
                };
            };
        };
    };
    upsert_setting_api_admin_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSettingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSettingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_summary_api_admin_costs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSummaryOut"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummaryOut"][];
                };
            };
        };
    };
    user_costs_api_admin_users__user_id__costs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCostDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_role_api_admin_users__user_id__role_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_stories_api_admin_stories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"][];
                };
            };
        };
    };
    flag_story_api_admin_stories__story_id__flag_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_admin_runs_get: {
        parameters: {
            query?: {
                failed_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_admin_runs__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_admin_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLog"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observability_jobs_api_observability_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    preview_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingest_api_ingest__ingest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_api_stories__story_id__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportFormatOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_export_api_stories__story_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bgm_exports_api_stories__story_id__bgm_exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportFormatOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bgm_export_api_stories__story_id__bgm_exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    story_events_api_stories__story_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A stream of progress events, one per SSE frame. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["ProgressEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
