import { useEffect, useState } from 'react'
import { AppHeader } from '../components/AppHeader'
import { formatError, mysteries } from '../api'
import type { User } from '../types'

export function MysteryCompose({ user, onHome, onLogout, onCreated }: { user: User; onHome: () => void; onLogout: () => void; onCreated: (id: string) => void }) {
  const [premise, setPremise] = useState(''); const [setting, setSetting] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  return <div className="app-frame"><AppHeader email={user.email} onHome={onHome} onLogout={onLogout} onCompose={() => undefined} compact /><main className="compose"><section className="compose-copy"><p className="eyebrow">Case file</p><h1>Create an infinite mystery.</h1><p className="lede">Every culprit, clue, and interrogation is generated for this case alone.</p></section><form className="compose-form" onSubmit={e => { e.preventDefault(); setBusy(true); mysteries.create({ premise, setting, tone: 'classic_whodunit', suspect_count: 4, difficulty: 'medium', duration_minutes: 20 }).then(r => onCreated(r.story_id)).catch(e => setError(formatError(e))).finally(() => setBusy(false)) }}><label className="compose-label">Premise<textarea required minLength={20} value={premise} onChange={e => setPremise(e.target.value)} rows={8} placeholder="A locked-room death on the final night of a monsoon festival…" /></label><label className="compose-label slim">Setting<input required value={setting} onChange={e => setSetting(e.target.value)} placeholder="An old hill-station hotel" /></label>{error && <p className="form-error">{error}</p>}<div className="compose-actions"><button className="btn ghost" type="button" onClick={onHome}>Cancel</button><button className="btn primary" disabled={busy}>{busy ? 'Opening case…' : 'Generate mystery'}</button></div></form></main></div>
}

export function Mystery({ user, storyId, onHome, onLogout, onCompose }: { user: User; storyId: string; onHome: () => void; onLogout: () => void; onCompose: () => void }) {
  const [data, setData] = useState<any>(null); const [error, setError] = useState<string | null>(null); const [question, setQuestion] = useState(''); const [selected, setSelected] = useState<string>('')
  const load = () => mysteries.get(storyId).then(r => { setData(r); if (!selected && r.case?.suspects?.[0]) setSelected(r.case.suspects[0].id) }).catch(e => setError(formatError(e)))
  useEffect(() => { load(); const timer = window.setInterval(load, 4000); return () => clearInterval(timer) }, [storyId])
  const c = data?.case
  return <div className="app-frame"><AppHeader email={user.email} onHome={onHome} onLogout={onLogout} onCompose={onCompose} compact /><main className="studio">{error && <p className="form-error">{error}</p>}{!c || !c.id ? <p className="muted loading-copy">Building your case file…</p> : <><section className="compose-copy"><p className="eyebrow">{c.setting}</p><h1>{c.title}</h1><p className="lede">{c.initial_scene}</p></section><section className="library-list"><h2>Suspects</h2><ul>{c.suspects.map((s: any) => <li key={s.id}><button className="story-row" onClick={() => setSelected(s.id)}><div><strong>{s.name}</strong><span className="muted">{s.role} — {s.public_alibi}</span></div></button></li>)}</ul><h2>Evidence</h2><ul>{c.clues.map((clue: any) => <li key={clue.id}><button className="story-row" onClick={() => !clue.locked && undefined}><div><strong>{clue.title}</strong><span className="muted">{clue.locked ? clue.discovery_requirement : clue.description}</span></div>{clue.locked && <button className="btn secondary" onClick={() => mysteries.discover(storyId, clue.id).then(load)}>Discover</button>}</button></li>)}</ul></section><section className="compose-form"><h2>Interrogate</h2><textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask a suspect about the night of the murder…" rows={3}/><div className="compose-actions"><button className="btn primary" disabled={!selected || !question} onClick={() => mysteries.interrogate(storyId, selected, question).then(() => { setQuestion(''); load() })}>Ask suspect</button><button className="btn secondary" disabled={!selected} onClick={() => mysteries.accuse(storyId, selected).then(r => { alert(r.message); load() })}>Accuse</button><button className="btn ghost" onClick={() => mysteries.reveal(storyId).then(load)}>Reveal solution</button></div>{c.interrogations?.map((x: any) => <p key={x.id}><strong>Suspect:</strong> {x.response}</p>)}{c.revealed && <section className="compose-copy"><h2>Solution</h2><p>{c.solution}</p><p>{c.reveal_scene}</p></section>}</section></>}</main></div>
}
